services:
  - type: web
    name: rediforge
    runtime: docker
    repo: https://github.com/Ashutosh-Yadav-256/Build-Redis-In-JAVA
    branch: main
    plan: free
    healthCheckPath: /health
    envVars:
      - key: REDIS_PASSWORD
        generateValue: true
      - key: PORT
        value: 10000
